[project]
name = "kurigram-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Keva1z", email = "Keva1z@yandex.ru" }
]
requires-python = ">=3.14"
dependencies = [
    "kurigram>=2.2.26",
    "uvloop>=0.23.0 ; sys_platform != 'win32'",
    "winloop>=0.7.1 ; sys_platform == 'win32'"
]

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
